# Generated by Django 5.1.1 on 2024-09-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Sucursal',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_pedido', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('fecha_germinacion', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_lote', models.CharField(max_length=50)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abonos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_semilla', models.IntegerField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('remision', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
            options={
                'db_table': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Intervinientes',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('rol', models.ForeignKey(db_column='Rol_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.roles')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.sucursal')),
            ],
            options={
                'db_table': 'Intervinientes',
            },
        ),
    ]
