# Generated by Django 5.1.1 on 2024-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_pedido_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='abonos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='pedido',
            table=None,
        ),
    ]
