# Generated by Django 5.1.1 on 2024-09-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_pedido_abonos_alter_pedido_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_abonada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_abono', models.DateField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_abonos', to='administracion.pedido')),
            ],
            options={
                'db_table': 'Abonos',
            },
        ),
    ]
