# Generated by Django 5.1.1 on 2024-09-11 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_abono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abono_set', to='administracion.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='abonos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='abono',
            table=None,
        ),
    ]
