# Generated by Django 5.1.1 on 2024-09-11 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_abono_pedido_alter_pedido_abonos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_abonos', to='administracion.pedido'),
        ),
    ]
