# Generated by Django 5.1.1 on 2024-09-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_abono_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.productos'),
        ),
    ]
