# Generated by Django 5.1.1 on 2024-09-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_alter_pedido_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='abonos',
        ),
    ]
