# Generated by Django 5.1.1 on 2024-09-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_remove_pedido_abonos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad_semilla',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
